---
- name: install httpd
  hosts: ansible-servers
  become: true
  become_user: root
  gather_facts: true
  tasks:
      - name: "Inatalling httpd"
        package: name=httpd state=present

      - name: "updating the virtual host entries"
        lineinfile:
         dest: /etc/httpd/conf/httpd.conf
         line: "<VirtualHost 18.188.43.43:80> \n servername www.devops-test.cit.com \n DocumentRoot '/var/www/html/' \n </VirtualHost>"
         state: present
         insertafter: EOF

      - name: "Installing PHP"
        yum: name=php state=present
      
     
      - name: "Changing Timezone"
        lineinfile:
         dest: /etc/php.ini
         regexp: "date.timezone ="
         line: "date.timezone = America/Eastern"

      - name: "Change Memory"
        lineinfile:
         dest: /etc/php.ini
         regexp: "memory_limit="
         line: "memory_limit = 512M"
    
      - name: "instal php-pecl-memcache"
        yum: name=php-pecl-memcache state=present

      - name: "Install memcached"
        yum: name=memcached state=present

      - name: "Edit memcached port number"
        lineinfile:
         dest: /etc/sysconfig/memcached
         regexp: "PORT="
         line: "PORT=11211, 11212, 11213, 11214"
     
      - name: "Edit memcached memory size"
        lineinfile:
         dest: /etc/sysconfig/memcached
         regexp: "CACHESIZE="
         line: "CACHESIZE=128"

      - name: "Enable and start memcached"
        service: name=memcached state=started enabled=yes   
    
      - name: "Enable and start the HTTPd"
        service: name=httpd state=started  enabled=yes

      - name: "Create Cron Job to restart memcached at every 2 minutes"
        cron:
          name: "restart memcached"
          minute: "*/2"
          job: "systemctl restart memcached" 
